definitions:
  db.CreateCTFParams:
    properties:
      author_id:
        type: integer
      description:
        type: string
      end_date:
        type: string
      name:
        type: string
      phrase:
        type: string
      start_date:
        type: string
    type: object
  db.CreateChallengeParams:
    properties:
      description:
        type: string
      flag:
        type: string
      name:
        type: string
      phrase:
        type: string
    type: object
  db.Ctf:
    properties:
      author_id:
        type: integer
      description:
        type: string
      end_date:
        type: string
      id:
        type: integer
      name:
        type: string
      phrase:
        type: string
      start_date:
        type: string
    type: object
  db.UpdateCTFParams:
    properties:
      description:
        type: string
      end_date:
        type: string
      name:
        type: string
      phrase:
        type: string
      start_date:
        type: string
    type: object
info:
  contact: {}
paths:
  /ctfs:
    post:
      consumes:
      - application/json
      description: Creates a new CTF and returns its ID
      parameters:
      - description: CTF details
        in: body
        name: ctf
        required: true
        schema:
          $ref: '#/definitions/db.CreateCTFParams'
      produces:
      - application/json
      responses:
        "200":
          description: '{\"ctf_id\": string}'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Create a CTF
      tags:
      - ctfs
  /ctfs/{phrase}:
    delete:
      description: Deletes a CTF by its mnemonic phrase
      parameters:
      - description: CTF phrase
        in: path
        name: phrase
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Deleted
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Delete a CTF
      tags:
      - ctfs
    put:
      consumes:
      - application/json
      description: Updates CTF details by its mnemonic phrase
      parameters:
      - description: CTF phrase
        in: path
        name: phrase
        required: true
        type: string
      - description: CTF update parameters
        in: body
        name: ctf
        required: true
        schema:
          $ref: '#/definitions/db.UpdateCTFParams'
      produces:
      - application/json
      responses:
        "200":
          description: Updated
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Update CTF details
      tags:
      - ctfs
  /ctfs/{phrase}/challenges:
    get:
      description: Returns all challenges for a specific CTF
      parameters:
      - description: CTF phrase
        in: path
        name: phrase
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of challenges
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get CTF challenges
      tags:
      - challenges
    post:
      consumes:
      - application/json
      description: Creates a new challenge for a CTF
      parameters:
      - description: CTF phrase
        in: path
        name: phrase
        required: true
        type: string
      - description: Challenge details
        in: body
        name: challenge
        required: true
        schema:
          $ref: '#/definitions/db.CreateChallengeParams'
      produces:
      - application/json
      responses:
        "200":
          description: Challenge created
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Create a challenge
      tags:
      - challenges
swagger: "2.0"
