// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: guest.sql

package db

import (
	"context"
	"database/sql"
)

const createGuest = `-- name: CreateGuest :execresult
INSERT INTO guests (
    nickname,
    ctf_id
) VALUES (
    ?, ?
)
`

type CreateGuestParams struct {
	Nickname string `json:"nickname"`
	CtfID    int32  `json:"ctf_id"`
}

func (q *Queries) CreateGuest(ctx context.Context, arg CreateGuestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createGuest, arg.Nickname, arg.CtfID)
}

const getGuestByID = `-- name: GetGuestByID :one
SELECT id, nickname, last_seen, created_at, ctf_id FROM guests
WHERE id = ? LIMIT 1
`

func (q *Queries) GetGuestByID(ctx context.Context, id int32) (Guest, error) {
	row := q.db.QueryRowContext(ctx, getGuestByID, id)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.LastSeen,
		&i.CreatedAt,
		&i.CtfID,
	)
	return i, err
}

const getGuestByNameAndCTF = `-- name: GetGuestByNameAndCTF :one
SELECT id, nickname, last_seen, created_at, ctf_id FROM guests
WHERE nickname = ? AND ctf_id = ? LIMIT 1
`

type GetGuestByNameAndCTFParams struct {
	Nickname string `json:"nickname"`
	CtfID    int32  `json:"ctf_id"`
}

func (q *Queries) GetGuestByNameAndCTF(ctx context.Context, arg GetGuestByNameAndCTFParams) (Guest, error) {
	row := q.db.QueryRowContext(ctx, getGuestByNameAndCTF, arg.Nickname, arg.CtfID)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.LastSeen,
		&i.CreatedAt,
		&i.CtfID,
	)
	return i, err
}

const markGuestSeen = `-- name: MarkGuestSeen :execresult
UPDATE guests
SET last_seen = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) MarkGuestSeen(ctx context.Context, id int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, markGuestSeen, id)
}

const pruneOldSessions = `-- name: PruneOldSessions :execresult
DELETE FROM guests
WHERE last_seen < DATE_SUB(NOW(), INTERVAL 3 MONTH)
`

func (q *Queries) PruneOldSessions(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, pruneOldSessions)
}
