// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Challenge struct {
	ID          int32
	CtfID       int32
	Name        string
	Description sql.NullString
	Flag        sql.NullString
	NoteID      sql.NullInt32
	CreatedAt   sql.NullTime
}

type ChallengeTag struct {
	ChallengeID int32
	TagID       int32
}

type Ctf struct {
	ID          int32
	Name        string
	Description sql.NullString
	StartDate   sql.NullTime
	EndDate     sql.NullTime
	AuthorID    sql.NullInt32
}

type Note struct {
	ID          int32
	ChallengeID int32
	CreatedBy   sql.NullInt32
}

type Session struct {
	ID        int32
	Cookie    string
	Nickname  string
	LastSeen  sql.NullTime
	CreatedAt sql.NullTime
}

type Tag struct {
	ID   int32
	Name string
}

type User struct {
	ID           int32
	Username     string
	PasswordHash sql.NullString
}
