// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Challenge struct {
	ID          int32        `json:"id"`
	CtfID       int32        `json:"ctf_id"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Flag        string       `json:"flag"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type ChallengeTag struct {
	ChallengeID int32 `json:"challenge_id"`
	TagID       int32 `json:"tag_id"`
}

type Ctf struct {
	ID          int32     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	StartDate   time.Time `json:"start_date"`
	EndDate     time.Time `json:"end_date"`
	AuthorID    int32     `json:"author_id"`
}

type Room struct {
	ID          uint64         `json:"id"`
	RoomID      int32          `json:"room_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Session struct {
	ID        int32        `json:"id"`
	Cookie    string       `json:"cookie"`
	Nickname  string       `json:"nickname"`
	LastSeen  sql.NullTime `json:"last_seen"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Tag struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID           int32  `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}
